version: 2.1

executors:
  node_executor:
    docker:
      - image: cimg/node:18.17

jobs:
  build-and-deploy:
    executor: node_executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build React app
          command: npm run build
      - run:
          name: Install non-interactive OCI CLI
          command: |
            export OCI_CLI_INSTALL_DIR="$HOME/lib/oracle-cli"
            export PATH="$OCI_CLI_INSTALL_DIR/bin:$PATH"
            bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" -- --accept-all-defaults
            echo 'export PATH=$PATH:$HOME/bin' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Set up OCI config and secure it
          command: |
            mkdir -p ~/.oci

            # write a minimal config
            printf "%s\n" \
              "[DEFAULT]" \
              "user=$OCI_USER_OCID" \
              "fingerprint=$OCI_FINGERPRINT" \
              "tenancy=$OCI_TENANCY_OCID" \
              "region=$OCI_REGION" \
              "key_file=/home/circleci/.oci/oci_api_key.pem" \
            > ~/.oci/config

            # decode and write the private key
            echo "$OCI_API_PRIVATE_KEY" | base64 -d > ~/.oci/oci_api_key.pem

            # extract & append the public key label
            openssl rsa -in ~/.oci/oci_api_key.pem -pubout \
              | sed '1d;$d' \
              | tr -d '\n' \
              | awk '{ print "OCI_API_KEY=\"" $0 "\"" }' \
              >> ~/.oci/config

            # lock down permissions
            chmod 600 ~/.oci/config ~/.oci/oci_api_key.pem

            oci setup repair-file-permissions --file ~/.oci/config

            node scripts/oci-upload.js

            oci os object bulk-upload \
              --bucket-name "$OCI_BUCKET_NAME" \
              --src-path dist \

workflows:
  build_and_deploy_workflow:
    jobs:
      - build-and-deploy